Add input configurations used for profiling
OrderN/CONQUEST-release pull request #262
Opened 2023-09-14 09:07 UTC by ilectra

These are systems we run for profiling, benchmarking, or scaling studies, thus they're too large to be run as CI tests.

2023-09-14 09:43 UTC, tkoskela requested changes
Could you change the base branch to `develop`?

2023-09-20 16:06 UTC, tkoskela approved these changes

2023-09-22 10:35 UTC, ilectra commented
@davidbowler could you please add a few words in a README for every benchmark? Otherwise we are ready to merge this.

2023-10-04 11:25 UTC, ilectra commented
> @davidbowler could you please add a few words in a README for every benchmark? Otherwise we are ready to merge this.

Moved it to #275 , we need to merge this PR.

2023-10-04 11:26 UTC, merged